version: "3.4"
services:
  besu.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 22.4.4
    ports:
      - 30303/tcp
      - 30303/udp
    volumes:
      - "data:/var/lib/besu"
    environment:
      EXTRA_OPTS: ""
      STORAGE_FORMAT: ""
      SYNC_MODE: ""
      CONFIG_MODE: normal
      WS_ENABLED: "true"
      RPC_ENABLED: "true"
      MAX_HTTP_CONNECTIONS: "100"
      BESU_OPTS: ""
    image: "besu.public.dappnode.eth:1.0.1"
    restart: unless-stopped
volumes:
  data: {}
