version: "3.4"
services:
  besu.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 22.4.0
    ports:
      - 30303/tcp
      - 30303/udp
    volumes:
      - "data:/var/lib/besu"
    environment:
      EXTRA_OPTS: ""
      STORAGE_FORMAT: ""
    image: "besu.public.dappnode.eth:22.4.0"
    restart: unless-stopped
volumes:
  data: {}
